### ISSUE TITLE
Block height and hash in oasis-sdk/client-sdk/go/types/CallResult

### ISSUE THREAD

**Issue by livelybug** [oasisprotocol/oasis-bridge#11]
Possible to add block height and block hash in "github.com/oasisprotocol/oasis-sdk/client-sdk/go/types/CallResult"?
The block height can be used for height comparison.

**Comment by kostko** [comment]
What is the use case for this? Currently this would require some additions to the runtime API.

**Comment by livelybug** [comment]
Scenario:
A fund transfer from Eth to Oasis.
The mint tx on Oasis failed for the 1st time.
Witness will not rollback immediately, as the Eth may charge much fee.
Instead, the witness will try the mint tx on Oasis a few times.
How many times to try? Depends on the block number of Oasis.
E.g, if the 1st failed attempt happened at block number 100.
Witness will keep retrying until the block number reaches 150.
That's where block number is needed.
As for the block hash, it's optional.

**Comment by livelybug** [comment]
Close, to get block height from tx's event.

**Comment by burtchensu** [comment]
Open #25 instead
