### ISSUE TITLE
How to find asset's symbol in the lock event

### ISSUE THREAD

**Issue by livelybug** [oasisprotocol/oasis-bridge#12]
The lock event: https://github.com/oasisprotocol/oasis-bridge/blob/master/examples/user-witness-flow/main.go#L323
Does it already contain the asset's symbol name? Like ROSE
If not, how to retrieve the asset's symbol name?

**Comment by kostko** [comment]
> Does it already contain the asset's symbol name? Like ROSE
> If not, how to retrieve the asset's symbol name?

The `Amount` type (`BaseUnits`) has a denomination attached. You can get it via `Amount.Denomination`. Note that this is the representation of the asset on the Oasis side. The bridge module has a mapping between these local (to the Oasis side) denominations and remote denominations (e.g., contract addresses in the case of Ethereum). We can add a query to convert between the two if this is needed.

**Comment by livelybug** [comment]
Yes, please add the query to convert the local denominations and remote denominations. 
I will make a corresponding converting logic for the ethereum side.

**Comment by livelybug** [comment]
Close, opne #26
