### ISSUE TITLE
Event of tx: fee & gas

### ISSUE THREAD

**Issue by burtchensu** [oasisprotocol/oasis-bridge#25]
As talked on slack, the full details of a tx will be contained in the tx's corresponding event,  instead of tx's callResult. To retrieve the details of a tx, the followings are needed:

* Tx Id contained in the tx's callResult
*  The event replied would have the following fields:
   + Tx fee
   + Tx gas_used / Tx gas price
   + Tx confirmation time on Oasis
   + The height of the block containing the tx
   + Additional charge for redeeming tx if Oasis chain charges for redeeming tx

**Comment by livelybug** [comment]
As talked on Slack(the caller specifies the ID in the body of the transaction. so you'd have to look at the request instead of the response),  the fields required change to:
Tx fee
Tx gas_used / Tx gas price
Tx confirmation time on Oasis

**Comment by livelybug** [comment]
Related to https://github.com/oasisprotocol/oasis-sdk/pull/94
