### ISSUE TITLE
Error code 5

### ISSUE THREAD

**Issue by livelybug** [oasisprotocol/oasis-bridge#41]
Steps to replicate the problem:
* Start Oasis core and bridge Runtime
* submit the 1st bridge.Release tx, good reply
```
ts=2021-04-09T13:44:32.218019578Z level=info module=oasis-ethereum caller=witness_oasis.go:486 msg="Oasis handle event from Ethereum" EthTxType=AssetLocked TxId=0xabcdf53a30bf666a334a799216b30082bfd003cdb107087ff336890b2ebd1b30 Amount=4300000000000000 User=0x569595234428B29F400a38B3E3DA09eBDBcCBC44
{"v":1,"call":{"method":"bridge.Release","body":"o2JpZABmYW1vdW50gkcPRtPEiMAARG9FVEhmdGFyZ2V0VQDI0PRZ2zjlzDHKd+ZtLERW3L61Ag=="},"ai":{"si":[{"pub":{"ed25519":"YgkEiVSR4SMQdfXw+ppuFYlqH0seutnCKk8KG8PyAx0="},"nonce":0}],"fee":{"amount":{"Amount":"0","Denomination":""},"gas":0}}}
{}
ts=2021-04-09T13:44:33.492496611Z level=debug module=oasis-ethereum caller=witness_oasis.go:289 side=handleEventOasis msg="seen new block" round=7
ts=2021-04-09T13:44:33.494025568Z level=info module=oasis-ethereum caller=witness_oasis.go:579 msg="Oasis tx log" TxType=AssetMinted nonce=55 WitnessAddress="YgkEiVSR4SMQdfXw+ppuFYlqH0seutnCKk8KG8PyAx0=" LatestRound=18446744073709551615 symbol=ETH amount=4300000000000000 sequences=0
ts=2021-04-09T13:44:33.494073774Z level=info module=oasis-ethereum caller=witness_oasis.go:583 msg="release successful"
```
* submit the 2nd bridge.Release tx, failed, error code: 5
```
ts=2021-04-09T13:46:01.475393754Z level=info module=oasis-ethereum caller=witness_oasis.go:486 msg="Oasis handle event from Ethereum" EthTxType=AssetLocked TxId=0x05cebd9f5e4d103af1849e508b62a051612d2112916c830ce043072e7db84796 Amount=4400000000000000 User=0x569595234428B29F400a38B3E3DA09eBDBcCBC44
{"v":1,"call":{"method":"bridge.Release","body":"o2JpZABmYW1vdW50gkcPocbVAwAARG9FVEhmdGFyZ2V0VQDI0PRZ2zjlzDHKd+ZtLERW3L61Ag=="},"ai":{"si":[{"pub":{"ed25519":"YgkEiVSR4SMQdfXw+ppuFYlqH0seutnCKk8KG8PyAx0="},"nonce":1}],"fee":{"amount":{"Amount":"0","Denomination":""},"gas":0}}}
{}
ts=2021-04-09T13:46:02.82870439Z level=debug module=oasis-ethereum caller=witness_oasis.go:289 side=handleEventOasis msg="seen new block" round=11
ts=2021-04-09T13:46:02.833180894Z level=error module=oasis-ethereum caller=utils.go:18 msg="failed to submit release transaction" err="module: bridge code: 5"
```

Error code 5 means sig already submitted. But the 2 tx are different, the 2nd one still supposed to fail?

Another issue: The amount is set like below, but the log showed that both amount and denomination are empty:
```
Amount: types.NewBaseUnits(*quantity.NewFromUint64(1000000000000000), types.Denomination("o"+"ETH")),
```

Oasis core version:
```
burt@17g:~/src/blk/cdot/oasis/oasis-core/oasis-core$ ./go/oasis-net-runner/oasis-net-runner --version
Software version: 21.0.1-gitd5e57721c
Go toolchain version: 1.15.8
```

**Comment by pro-wh** [comment]
The signatures have to come from different witnesses. Two signatures from the same witness (signed by `YgkEiVSR4SMQdfXw+ppuFYlqH0seutnCKk8KG8PyAx0=` in this case) count as redundant, and I think it's correctly saying that the witness already signed

**Comment by livelybug** [comment]
From a user's perspective, any reason the tx 2 below should fail? 
Tx 1: the user transfers 0.0043 eth to Oasis, successful
Tx 2: the user transfers 0.0044 eth to Oasis, failure

**Comment by kostko** [comment]
The way it currently works is that the witnesses need to process transactions in sequence, so the previous release must complete (all witnesses sign) before the next one can proceed. Maybe you are processing Tx 2 before the quorum of witnesses have signed Tx 1?

**Comment by livelybug** [comment]
Thanks for the tip, after setting the witness as Bob and Charlie,  the issue is gone.
In my testing, if Tx 1 failed(not signed by the quorum of witnesses), all of the subsequent Tx will fail.
Is it the SDK's normal behavior or I am doing something wrong?

**Comment by kostko** [comment]
> In my testing, if Tx 1 failed(not signed by the quorum of witnesses), all of the subsequent Tx will fail.

Can you give some detail on what the transactions are and how the subsequent transactions will fail? Are these release transactions? Release transactions should start succeeding as soon as witnesses agree what was the next event on the remote chain.

As long as there is no agreement on the next event, there can be no progress or at least I don't see a safe way to continue.

Is the Ethereum part issuing monotonically incrementing sequence numbers for each release event? Because in this case the witnesses should all see the same events and agree on them.

**Comment by livelybug** [comment]
Scenario same as above, here are details:
* There are 2 witnesses working on the bridge, thredshold of witnees signature is 2.
* Tx 1: the user transfers 0.0043 eth to Oasis, which requests a release tx on Oasis chain, but one witness failed to sign the tx.
* All subsequent tx, like tx 1, which are from ETH to Oasis, will fail.

> Release transactions should start succeeding as soon as witnesses agree what was the next event on the remote chain.
> As long as there is no agreement on the next event, there can be no progress or at least I don't see a safe way to continue.

I understand the logic you described from a technical perspective: the bridge runtime should not skip tx. 
I was thinking if there's anything we can do to enhance the user experience.

Here is a proposal: 
* Tx 1 is not signed by only one witnesses.
* Request of Tx 2 is received by Oasis chain. 
* **At this moment, the bridge runtime saves the request of tx 2, reply with a pending status instead of an error.** 
* **The bridge runtime waits until Tx 1 is signed by all witnesses, then emit successful tx events of both Tx 1 and Tx 2.** 

> Is the Ethereum part issuing monotonically incrementing sequence numbers for each release event?

Yes, the ```monotonically incrementing sequence numbers``` is named ```_eventNonce``` in ETH contract. But the ```_eventNonce``` is not passed to Oasis chain. Is it possible that the witness can pass _eventNonce to Oasis chain by setting _eventNonce in the tx's payload? This variable can help with auditing, and some possible conflict tx analysis in the future, in my opinion.

**Comment by kostko** [comment]
>  Is it possible that the witness can pass _eventNonce to Oasis chain by setting _eventNonce in the tx's payload? This variable can help with auditing, and some possible conflict tx analysis in the future, in my opinion.

Yes this is exactly what it should already be doing. The field in the `Release` payload is called `id`. I think that if you set that field to the value emitted on the ETH side, your problem should also be solved. Note that the assumption is that it starts with zero, but we can add parameters for initial sequence numbers if needed.

**Comment by livelybug** [comment]
> The field in the Release payload is called id. I think that if you set that field to the value emitted on the ETH side, 

Double confirm: The field ```ID``` in struct ```Release``` is the tx ID of the release tx, whose current value is ```sequences.Incoming```.   Replacing the value with ```_eventNonce``` from ETH contract will also affect the tx ID.

> your problem should also be solved

I am not sure if it would be resolved, let me do some testing first.

**Comment by livelybug** [comment]
The field ID in struct Release is set as _eventNonce from ETH contract, and the normal asset transfer from ETH to Oasis is successful.

The subsequent testing hit error:
* There are 2 witnesses Bob and Charlie;
* Charlie is down out of sudden;
* Release Tx 1: only signed by Bob;
* Release Tx 2: only signed by Bob;
* Charlie restarts and up;
* Charlie detects tx 1 and tx 2; 
* Charlie signs tx 1 and tx 2; Both get "Release successfully".
* **No event of tx 1 and tx 2 listened by the witness.**
* **Release Tx 3: hit invalid sequence number error.**

**Comment by kostko** [comment]
Can you provide the code that you use to test this? Or exact transactions.

**Comment by livelybug** [comment]
Code:
witness send release tx - https://github.com/octopus-network/oasis-ethereum/blob/main/witness_oasis.go#L495
witness listen for release event - https://github.com/octopus-network/oasis-ethereum/blob/main/witness_oasis.go#L573

>  Or exact transactions.

Correct my last comment, the event of Tx 1 is found. Let me know if the log is not enough.

Bob:
TX 1 - 
ts=2021-04-22T10:08:15.227090002Z level=info module=oasis-ethereum caller=witness_oasis.go:497 msg="Oasis handle event from Ethereum" EthTxType=AssetLocked TxId=0xab3eaf7f19d3cbe6890d4538bd398740be451f267d09a5439ba85ca5297da951 Amount=180700000000000 User=0x569595234428B29F400a38B3E3DA09eBDBcCBC44
{"v":1,"call":{"method":"bridge.Release","body":"o2JpZAFmYW1vdW50gkakWH9PmABEb0VUSGZ0YXJnZXRVAPOPeewebP6XtP4Gx4mLUqj620eD"},"ai":{"si":[{"pub":{"ed25519":"8l1AQE+ETOPLckiNJ7NOD+AfZdaPw6wguir/vSF11YI="},"nonce":1}],"fee":{"amount":{"Amount":"0","Denomination":""},"gas":0}}}
{}
ts=2021-04-22T10:08:16.585052831Z level=debug module=oasis-ethereum caller=witness_oasis.go:289 side=handleEventOasis msg="seen new block" round=8
ts=2021-04-22T10:08:16.587820789Z level=info module=oasis-ethereum caller=witness_oasis.go:578 msg="Oasis tx log" TxType=AssetMinted nonce=1 WitnessAddress="8l1AQE+ETOPLckiNJ7NOD+AfZdaPw6wguir/vSF11YI=" LatestRound=18446744073709551615 symbol=ETH amount=180700000000000
ts=2021-04-22T10:08:16.588021931Z level=info module=oasis-ethereum caller=witness_oasis.go:582 msg="release successful"

TX 2 - 
ts=2021-04-22T10:09:25.139377332Z level=info module=oasis-ethereum caller=witness_oasis.go:497 msg="Oasis handle event from Ethereum" EthTxType=AssetLocked TxId=0x118ea0bcc890277fb38733c204eb6555a17703e52a2a996e54aff8751071fbc8 Amount=180800000000000 User=0x569595234428B29F400a38B3E3DA09eBDBcCBC44
{"v":1,"call":{"method":"bridge.Release","body":"o2JpZAJmYW1vdW50gkakb8fGgABEb0VUSGZ0YXJnZXRVAPOPeewebP6XtP4Gx4mLUqj620eD"},"ai":{"si":[{"pub":{"ed25519":"8l1AQE+ETOPLckiNJ7NOD+AfZdaPw6wguir/vSF11YI="},"nonce":2}],"fee":{"amount":{"Amount":"0","Denomination":""},"gas":0}}}
{}
ts=2021-04-22T10:09:26.428365989Z level=debug module=oasis-ethereum caller=witness_oasis.go:289 side=handleEventOasis msg="seen new block" round=12
ts=2021-04-22T10:09:26.431058651Z level=error module=oasis-ethereum caller=utils.go:19 msg="failed to submit release transaction" err="module: bridge code: 3"

TX 3 -
ts=2021-04-22T10:20:37.096248055Z level=info module=oasis-ethereum caller=witness_oasis.go:497 msg="Oasis handle event from Ethereum" EthTxType=AssetLocked TxId=0x2edd1ca3c346c13829f0cd95ad8b42cb2f187b402ad1c16079f4130301d7ec31 Amount=181900000000000 User=0x569595234428B29F400a38B3E3DA09eBDBcCBC44
{"v":1,"call":{"method":"bridge.Release","body":"o2JpZANmYW1vdW50gkalb+TieABEb0VUSGZ0YXJnZXRVAPOPeewebP6XtP4Gx4mLUqj620eD"},"ai":{"si":[{"pub":{"ed25519":"8l1AQE+ETOPLckiNJ7NOD+AfZdaPw6wguir/vSF11YI="},"nonce":3}],"fee":{"amount":{"Amount":"0","Denomination":""},"gas":0}}}


Charlie:
TX 1 -
ts=2021-04-22T10:11:48.369717806Z level=info module=oasis-ethereum caller=witness_oasis.go:497 msg="Oasis handle event from Ethereum" EthTxType=AssetLocked TxId=0xab3eaf7f19d3cbe6890d4538bd398740be451f267d09a5439ba85ca5297da951 Amount=180700000000000 User=0x569595234428B29F400a38B3E3DA09eBDBcCBC44
{"v":1,"call":{"method":"bridge.Release","body":"o2JpZAFmYW1vdW50gkakWH9PmABEb0VUSGZ0YXJnZXRVAPOPeewebP6XtP4Gx4mLUqj620eD"},"ai":{"si":[{"pub":{"ed25519":"YgkEiVSR4SMQdfXw+ppuFYlqH0seutnCKk8KG8PyAx0="},"nonce":1}],"fee":{"amount":{"Amount":"0","Denomination":""},"gas":0}}}
ts=2021-04-22T10:11:49.195710466Z level=debug module=oasis-ethereum caller=witness_oasis.go:289 side=handleEventOasis msg="seen new block" round=17
ts=2021-04-22T10:11:49.19690531Z level=info module=oasis-ethereum caller=witness_oasis.go:578 msg="Oasis tx log" TxType=AssetMinted nonce=1 WitnessAddress="YgkEiVSR4SMQdfXw+ppuFYlqH0seutnCKk8KG8PyAx0=" LatestRound=18446744073709551615 symbol=ETH amount=180700000000000
ts=2021-04-22T10:11:49.197033638Z level=info module=oasis-ethereum caller=witness_oasis.go:582 msg="release successful"
ts=2021-04-22T10:11:49.198047219Z level=debug module=oasis-ethereum caller=witness_oasis.go:318 msg="got event of type AssetReleased" key="YnJpZGdlAAAAAg==" value=o2JpZAFmYW1vdW50gkakWH9PmABEb0VUSGZ0YXJnZXRVAPOPeewebP6XtP4Gx4mLUqj620eD

TX 2 -
ts=2021-04-22T10:11:49.197075392Z level=info module=oasis-ethereum caller=witness_oasis.go:497 msg="Oasis handle event from Ethereum" EthTxType=AssetLocked TxId=0x118ea0bcc890277fb38733c204eb6555a17703e52a2a996e54aff8751071fbc8 Amount=180800000000000 User=0x569595234428B29F400a38B3E3DA09eBDBcCBC44
{"v":1,"call":{"method":"bridge.Release","body":"o2JpZAJmYW1vdW50gkakb8fGgABEb0VUSGZ0YXJnZXRVAPOPeewebP6XtP4Gx4mLUqj620eD"},"ai":{"si":[{"pub":{"ed25519":"YgkEiVSR4SMQdfXw+ppuFYlqH0seutnCKk8KG8PyAx0="},"nonce":2}],"fee":{"amount":{"Amount":"0","Denomination":""},"gas":0}}}

TX 3 - 
ts=2021-04-22T10:20:37.100649006Z level=info module=oasis-ethereum caller=witness_oasis.go:497 msg="Oasis handle event from Ethereum" EthTxType=AssetLocked TxId=0x2edd1ca3c346c13829f0cd95ad8b42cb2f187b402ad1c16079f4130301d7ec31 Amount=181900000000000 User=0x569595234428B29F400a38B3E3DA09eBDBcCBC44
{"v":1,"call":{"method":"bridge.Release","body":"o2JpZANmYW1vdW50gkalb+TieABEb0VUSGZ0YXJnZXRVAPOPeewebP6XtP4Gx4mLUqj620eD"},"ai":{"si":[{"pub":{"ed25519":"YgkEiVSR4SMQdfXw+ppuFYlqH0seutnCKk8KG8PyAx0="},"nonce":3}],"fee":{"amount":{"Amount":"0","Denomination":""},"gas":0}}}

**Comment by kostko** [comment]
Bob's TX 2 received the `InvalidSequenceNumber` error, possibly because it was submitted before TX 1 was finalized (signed by both witnesses). Bob should only be submitting TX 2 after seeing the release event for TX 1. Also in case submission fails, it should probably retry submission.

**Comment by livelybug** [comment]
> Bob should only be submitting TX 2 after seeing the release event for TX 1

It's not difficult to implement this feature in witness. But the logic, although I don't see it would cause errors immediately,  doesn't look so rational. In my opinion, Witness's job is signing and sending tx, instead of holding user's tx; Further more, witness may come and go, holding user's tx may increase the risk of tx lost.

What do you think of my proposal  [here](https://github.com/oasisprotocol/oasis-bridge/issues/41#issuecomment-823824642)?

> Also in case submission fails, it should probably retry submission.

It's being developed.

**Comment by kostko** [comment]
> It's not difficult to implement this feature in witness. But the logic, although I don't see it would cause errors immediately, doesn't look so rational. In my opinion, Witness's job is signing and sending tx, instead of holding user's tx; Further more, witness may come and go, holding user's tx may increase the risk of tx lost.

So the alternative is for the runtime to hold pending events in state. But in that case the set of pending events can grow unbounded if one of the witnesses is down. And if we add a limit to that queue then you basically have the same problem, just with a delay. I think that having the queue off-chain is better.

**Comment by livelybug** [comment]
I think we don't need to worry much about the explosion size of the event queue for now. As the TPS is restricted by Etherium's capability.
As for the long term, one possible solution for off-chain pending event queue would be something like substrate's off-chain worker.

**Comment by kostko** [comment]
I mean if you make sure that witnesses only submit release for event E after confirming that event E-1 has been accepted, this implicitly moves to queue to the witnesses and thus off-chain. No other stuff required.
