### ISSUE TITLE
value of "sequences.Incoming" always 0 in "bridge.Release" 

### ISSUE THREAD

**Issue by livelybug** [oasisprotocol/oasis-bridge#42]
As the title, value of "sequences.Incoming" always 0 in "bridge.Release", is "sequences.Incoming" the unique ID of "bridge.Release" tx? 
```go
	tx := types.NewTransaction(nil, "bridge.Release", Release{
		ID:     sequences.Incoming,
		Target: w.account,
		Amount: types.NewBaseUnits(*quantity.NewFromUint64(amount), types.Denomination("o"+ev.Symbol)),
		//Amount: types.NewBaseUnits(*quantity.NewFromUint64(amount), types.Denomination("o"+"ETH")),
	})
```

**Comment by kostko** [comment]
> As the title, value of "sequences.Incoming" always 0 in "bridge.Release", is "sequences.Incoming" the unique ID of "bridge.Release" tx?

The incoming sequence number should advance once the threshold of witnesses have executed the release transaction. Are you sure the required number of witnesses have signed?

**Comment by livelybug** [comment]
The same solution of #41
