### ISSUE TITLE
Not able to find event of "bridge.Release" tx

### ISSUE THREAD

**Issue by livelybug** [oasisprotocol/oasis-bridge#43]
The "bridge.Release" tx below is successful: 
```
ts=2021-04-12T01:57:06.322152767Z level=info module=oasis-ethereum caller=witness_oasis.go:495 msg="Oasis handle event from Ethereum" EthTxType=AssetLocked TxId=0xfc4a718253dd610162503b02d7ee7bcc54c97fc71b01b2fd514f3389e493c6ff Amount=5500000000000000 User=0x569595234428B29F400a38B3E3DA09eBDBcCBC44
{"v":1,"call":{"method":"bridge.Release","body":"o2JpZABmYW1vdW50gkcTijiKQ8AARG9FVEhmdGFyZ2V0VQDI0PRZ2zjlzDHKd+ZtLERW3L61Ag=="},"ai":{"si":[{"pub":{"ed25519":"YgkEiVSR4SMQdfXw+ppuFYlqH0seutnCKk8KG8PyAx0="},"nonce":0}],"fee":{"amount":{"Amount":"0","Denomination":""},"gas":0}}}
```

But the event of the tx is not found in incoming blocks.

**Comment by kostko** [comment]
Has the threshold of witnesses signed? The event is only emitted once the required number of witnesses (as configured) sign.

**Comment by livelybug** [comment]
Got it. It's settled after setting the witness as Bob and Charlie, as  #41 
Now the question is: the ```types.CallResult``` of a tx cannot indicate the tx's status, because other witnesses may fail to sign. Under such circumstances,  any way to get the tx's final status?

**Comment by kostko** [comment]
Currently the quorum of witnesses must sign before there can be progress on any specific sequence number -- e.g., you cannot skip sequence numbers and there are no timeouts. Are you proposing this should be handled differently? If the quorum of witnesses disagrees on a specific event (e.g., a specific sequence number) I don't see how this can safely make progress?

**Comment by livelybug** [comment]
Currently, after submitting a tx, and the ```types.CallResult``` is successful, the tx's status would be pending, until there's an event of the tx.
If no event received, the tx's status will always be pending.  It's not a show stopper, but is it a minor issue for this project?

**Comment by kostko** [comment]
> If no event received, the tx's status will always be pending. It's not a show stopper,

But wouldn't this indicate that something is wrong with the witnesses, e.g. there is no agreement on the next event that happened on the remote chain?

**Comment by livelybug** [comment]
Ok, let's treat the status pending as something wrong.
