### ISSUE TITLE
Implementation of witness' signature

### ISSUE THREAD

**Issue by livelybug** [oasisprotocol/oasis-bridge#44]
The witness' signature is expected to use the same algorithm of JS bleow:
```js
let sha = web3.utils.soliditySha3(5,accounts[8],"lax1hymccqtr6r90rnmtg7nh8sxpgns9jc24x33hyp","ETH",new BN('40000',10));  
let sign0 = await web3.eth.sign(sha,accounts[0]);
let sign2 = await web3.eth.sign(sha,accounts[2]);
let sigs = {gs_index:0,g_indexs:[0,2],sigs:[sign0,sign2]};  // gs_index: guardian set index; g_indexs: index of guardian signing the tx 
```

```5,accounts[8],"lax1hymccqtr6r90rnmtg7nh8sxpgns9jc24x33hyp","ETH",new BN('40000',10)``` are payload of the tx:
```
{_nonce:5, _localAddress:accounts[8],_remoteAddress:"lax1hymccqtr6r90rnmtg7nh8sxpgns9jc24x33hyp",_symbol:"ETH",_amount:40000}
```

**Comment by lcosent** [comment]
@kostko

**Comment by kostko** [comment]
I think this requires https://github.com/oasisprotocol/oasis-sdk/issues/95 if you want to be able to use secp256k1 keys with the Go client SDK -- at least that was my understanding. @livelybug please confirm that this (secp256k1 signer support in the Go client SDK) is what the issue is about?

**Comment by livelybug** [comment]
Yes, the ECDSA algorithm with secp256k1 constants is expected to be used by witnesses to sign tx payload's hash. 
The payload's hash is generated by Keccak256.

**Comment by livelybug** [comment]
> So your question is how to sign ParaTime transactions using the secp256k1 signer?

A user submitted an lock tx.
```
ts=2021-04-27T01:51:25.405847532Z level=debug module=oasis-ethereum caller=witness_oasis.go:386 msg="got lock event" id=0 target=0000000000000000000000000000000000000000 owner=oasis1qrec770vrek0a9a5lcrv0zvt22504k68svq7kzve amount="950000000000 oETH"
```
And observed the witness sign event:
```
op: {lock: {…}}
sigs: (2) [Uint8Array(54), Uint8Array(54)]
wits: (2) [1, 0]
```

The question is: How to code with the Go SDK, to make the ```sigs[n]``` in the witness sign event is composed by below:
* Generate payload's hash by Keccak256, pseudo code
```
hash = Keccak256(nonce, account_address, target_account_address, symbol, amount)
```
* witness sign the hash by secp256k1, pseudo code
```
sigs[n] = secp256k1(hash)
```

**Comment by kostko** [comment]
This is Ethereum-specific and not part of our SDK. You should use one of the Ethereum Go libraries to compute the keccak256 hash and signature?

The part that can now be done in our SDK (since oasisprotocol/oasis-sdk#95) is that you can also use the same secp256k1 key that you use in the above operation for witness keys. This can be used in the same way as any other signer for ParaTime transactions:
```golang
import "github.com/oasisprotocol/oasis-sdk/client-sdk/go/crypto/signature/secp256k1"

	// The private key should correspond to what is used by the witnesses. Note that this requires
	// that the appropriate public key is configured in the authorized witness list.
	signer := secp256k1.NewSigner(rawPrivateKey)

	tx.AppendSignerInfo(signer.Public(), nonce)
	stx := tx.PrepareForSigning()
	stx.AppendSign(chainCtx, signer)

	// Submit stx.UnverifiedTransaction() as usual.
```

**Comment by livelybug** [comment]
Thanks, As for the ```authorized witness list```, is it set on Oasis chain? If yes, any API to configure it?

**Comment by livelybug** [comment]
As per talked on Slack with Warren, the authorized witness list is still fixed in runtime initialization code.
how to get the ```rawPrivateKey```  of the fixed witnesses?
Using the example key [here](https://github.com/oasisprotocol/oasis-sdk/blob/main/client-sdk/go/crypto/signature/secp256k1/secp256k1_test.go#L17) hit error :
```
 err="client: transaction check failed"
```

**Comment by livelybug** [comment]
Witness code hang on ```Accounts.Nonce``` method, steps:

* Update oasis-bridge repo and compile
* Set ```testing.TestKey``` as secp256k1 signer(Dave) in witness, as below:
```

func NewTestKey(seed string) testing.TestKey {
	pk := sha512.Sum512_256([]byte(seed))
	signer := secp256k1.NewSigner(pk[:])
	return testing.TestKey{
		Signer:  signer,
		Address: types.NewAddress(signer.Public()),
	}}
```
* Trigger release tx
* Witness hang on the nonce method [here](https://github.com/octopus-network/oasis-ethereum/commit/8258c8f4de60f0e587c8655de6f15fccaf4e1b25#diff-f6360600746dcec88f8cc5a6262deceece08d0b2f3ca9292fd7d66c86c8ebc15R506), which never reponsed
```
Cli.Accounts.Nonce(ctx, client.RoundLatest, types.NewAddress(w.signer.Signer.Public()))
```

**Comment by livelybug** [comment]
Is multiple secp256 signer supported in current verion?
Setting multiple secp256 signer hit error, steps:
* set both Bob and Charlie as secp256 singer in oasis-bridge's ```src/testing/keys.rs```
```rust
test_key_ed25519!("A", alice, "NcPzNW3YU2T+ugNUtUWtoQnRvbOL9dYSaBfbjHLP1pE=");
test_key_secp256k1!("B", bob, "YgkEiVSR4SMQdfXw+ppuFYlqH0seutnCKk8KG8PyAx0=");
test_key_secp256k1!("C", charlie, "8l1AQE+ETOPLckiNJ7NOD+AfZdaPw6wguir/vSF11YI=");
test_key_secp256k1!("D", dave, "AwF6GNjbybMzhi3XRj5R1oTiMMkO1nAwB7NZAlH1X4BE");
```
* re-compile oasis-bridge
* run oasis-net-runner
* witness hit error
```
level=error module=grpc/client caller=grpc.go:244 ts=2021-05-14T10:48:24.283702816Z msg="request failed" method=/oasis-core.RuntimeClient/Query req_seq=8 rsp="unsupported value type" err="rpc error: code = Unknown desc = channel closed"
ts=2021-05-14T10:48:24.283769055Z level=error module=oasis-ethereum caller=utils.go:24 msg="failed to fetch account nonce" err="rpc error: code = Unknown desc = channel closed"
```

**Comment by kostko** [comment]
It seems that you simply renamed the function call to treat it as a Secp256k1 key without actually changing the key itself? This won't work as Ed25519 and Secp256k1 keys are not interchangeable.

You should instead generate proper Secp256k1 keys and put the public keys there. For example you can generate them in Go with:
```golang
privKey := sha512.Sum512_256([]byte("my nice little test key"))
signer := secp256k1.NewSigner(privKey[:])
pubKeyB64, _ := signer.Public().MarshalText()
fmt.Println(pubKeyB64)
```

And then configure in the runtime genesis state as:
```rust
 witnesses: vec![ 
     sdk::testing::keys::bob::pk(), 
     sdk::testing::keys::charlie::pk(), 
     sdk::testing::keys::dave::pk(), 
     sdk::crypto::signature::PublicKey::Secp256k1("base64-encoded-publickey-you-got-from-go".into()),
 ], 
```

**Comment by livelybug** [comment]
Thanks, maybe my question is not clear, the question is: it works well on signle secp256k1 signer, but how to modify the code to support multiple   secp256k1 signer?

The secp256k1 signature works well on **SINGLE** witness mode, like below:

* The Secp256k1 keys are generated in golang as below:
https://github.com/octopus-network/oasis-ethereum/blob/bbdda9bedc0fdaa75724c7f32435666b4da7e609/src/utils.go#L70-L89

*  oasis-bridge's src/testing/keys.rs
```rust
test_key_ed25519!("A", alice, "NcPzNW3YU2T+ugNUtUWtoQnRvbOL9dYSaBfbjHLP1pE=");
test_key_ed25519!("B", bob, "YgkEiVSR4SMQdfXw+ppuFYlqH0seutnCKk8KG8PyAx0=");
test_key_ed25519!("C", charlie, "8l1AQE+ETOPLckiNJ7NOD+AfZdaPw6wguir/vSF11YI=");
test_key_secp256k1!("D", dave, "AwF6GNjbybMzhi3XRj5R1oTiMMkO1nAwB7NZAlH1X4BE");
```
*  oasis-bridge's examples/runtime/src/lib.rs
```rust
                    witnesses: vec![
                        sdk::testing::keys::bob::pk(),
                        sdk::testing::keys::charlie::pk(),
                        sdk::testing::keys::dave::pk(),
                    ],
                    threshold: 1,
```

Is possible to make it support **multiple** secp256k1 witnesses? I tried like [this](https://github.com/oasisprotocol/oasis-bridge/issues/44#issuecomment-841174042) but failed. the threshold is set to 2.

**Comment by kostko** [comment]
Yes, it will work if you actually used Secp256k1 keys. Re-read my reply above, so you need to specify correct Secp256k1 keys. The reason why what you tried above (in https://github.com/oasisprotocol/oasis-bridge/issues/44#issuecomment-841174042) did not work was because you specified a **malformed Secp256k1 public key (since you wanted to just reuse Ed25519 key which can't possibly work)**.

See my comment above on how to generate valid Secp256k1 keys.
