### ISSUE TITLE
type of roothash.AnnotatedBlock.Height

### ISSUE THREAD

**Issue by burtchensu** [oasisprotocol/oasis-bridge#5]
change type of ```roothash.AnnotatedBlock.Height``` from int64 to uint64

**Comment by kostko** [comment]
You should not be using `AnnotatedBlock.Height` as that is the block height of the commitment at the consensus layer. The correct field is `AnnotatedBlock.Block.Header.Round` which is already a `uint64`.

**Comment by kostko** [comment]
Note that this is also shown in the example.
