### ISSUE TITLE
target address in lock event always 0

### ISSUE THREAD

**Issue by livelybug** [oasisprotocol/oasis-bridge#50]
Does the lock tx in js have a parameter for target address?
```js
const id = await userOut('alice', new oasis.signature.BlindContextSigner(alice), [oasis.quantity.fromBigInt(10), oasis.misc.fromString('oETH')], consensusChainContext);
```

The in the lock event listened by witness, the target address is always 0
```
ts=2021-05-22T12:57:42.073532673Z level=debug module=oasis-ethereum caller=witness_oasis.go:394 msg="got lock event" id=15 target=0000000000000000000000000000000000000000 owner=oasis1qrec770vrek0a9a5lcrv0zvt22504k68svq7kzve amount="2057 oETH"
```

**Comment by kostko** [comment]
Yes of course, the lock transaction has a `target` field:
https://github.com/oasisprotocol/oasis-bridge/blob/b39b9e54725763d15d4721f9726d15c8da7790fd/module-bridge/src/types.rs#L143-L152

Which is also used in the Go example:
https://github.com/oasisprotocol/oasis-bridge/blob/b39b9e54725763d15d4721f9726d15c8da7790fd/examples/user-witness-flow/main.go#L208-L213

**Comment by pro-wh** [comment]
I'm opening a PR to move this to a parameter in `userOut` to make this easier to see in the playground script (#51). But feel free not to use that code. It doesn't have some nice features like retrying on network problem. It's still only test code.

**Comment by livelybug** [comment]
I saw this issue is addressed in https://github.com/oasisprotocol/oasis-bridge/pull/51, can you also update the npm with the PR? if it's not updated yet.

**Comment by pro-wh** [comment]
#51 is a change to internal test code (`userOut` in playground.js), which we aren't distributing in the package on npm. The package only has the library code, which is more like `bridgeWrapper.callLock().setBody({target: ...})`. The library should have already supported `target` in the Lock tx body.

**Comment by livelybug** [comment]
oops, my fault. It's been a while since the last time I touch the js sdk, and I thought ```userOut``` was an API from npm.
