### ISSUE TITLE
How to get consistent address of one user in Go and Js SDK

### ISSUE THREAD

**Issue by livelybug** [oasisprotocol/oasis-bridge#53]
When a user is transferring assets from Oasis to Eth, witnesses sign a message that contains the user's Oasis account address.
But the user's Oasis address extracted in Js and Go SDK are different.

The user being tested is ```alice``` from seed 'oasis-runtime-sdk/test-keys: alice'

In go SDK, from the lock event, the ```owner``` field's value is: oasis1qrec770vrek0a9a5lcrv0zvt22504k68svq7kzve

In js SDK, the code below prints address different:
```js
    const aliceAddress = await oasis.staking.addressFromPublicKey(alice.public());
    const _1 = String.fromCharCode(...new Uint8Array(aliceAddress));
    const base64Add = btoa(base64String1);
    console.log("aliceAddress: " + aliceAddress);
    console.log("_1: " + _1);
    console.log("base64Add: " + base64Add);
``` 
print
```
aliceAddress: 0,243,143,121,236,30,108,254,151,180,254,6,199,137,139,82,168,250,219,71,131
_1: 
base64Add: APOPeewebP6XtP4Gx4mLUqj620eD
```

Alice's correct address in base64: NcPzNW3YU2T+ugNUtUWtoQnRvbOL9dYSaBfbjHLP1pE=

**Comment by kostko** [comment]
> Alice's correct address in base64: NcPzNW3YU2T+ugNUtUWtoQnRvbOL9dYSaBfbjHLP1pE=

This looks like a public key, not an address.

If you want a Bech32-encoded address you should do:
```typescript
const aliceAddressBech32 = await oasis.staking.addressToBech32(aliceAddress);
console.log(aliceAddressBech32);
```
