### ISSUE TITLE
submit witness transaction: invalid nonce

### ISSUE THREAD

**Issue by livelybug** [oasisprotocol/oasis-bridge#60]
The nonce is retrieved [here](https://github.com/octopus-network/oasis-ethereum/blob/971bad36b848d863b250a227d016c7327e5ef761/src/witness_oasis.go#L426).

I cannot replicate this problem, it seems only to happen when an incoming and an outgoing tx were submitted in the meanwhile.

Please refer to the attachment for the log.

[submitwitnesstransaction-invalidnonce.log](https://github.com/oasisprotocol/oasis-bridge/files/6822963/submitwitnesstransaction-invalidnonce.log)

**Comment by ptrus** [comment]
Based on the following log line:
```
ts=2021-07-15T11:48:43.150064307Z level=info module=oasis-ethereum caller=witness_oasis.go:619 msg="release successful"
```
it looks like `bridge.Release` transaction was submitted at about the same time, while you also tried to do `bridge.Witness`? 
The same signer is used for both transaction so what probably happened was:

```
1) query for nonce returned (for `bridge.Witness`) returned `52`
2) in parallel the `bridge.Release` transaction was submitted, bumping the account nonce to `53`
3) `bridge.Witness` with nonce `52` failed
```

You either need to make sure no transactions (by the same signer) are getting submitted concurrently, or implement retrying for "invalid nonce" errors.
